Tiny chores (#6)
* Add project name

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Refactor cmakefiles and add tests folder

Add tests folder.
Restructure cmakefiles to make building and running tests slightly
easier.
Add basic stuff into README.

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Adjust the unit test tools to the new building way

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Link the dynamic boost log lib

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Make BUILD_DOCKERAPP optional

Make BUILD_DOCKERAPP is an optional build argument.
Add a compile definition BUILD_DOCKERAPP if BUILD_DOCKERAPP is ON.

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Add 'tmp*' produced by tests to .gitignore

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Include dirs per target

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Define two types of builds, aklite and aktualizr

Effectively, we build two types of builds by using the given repo.
1. SOTA_TOOLS - the goal is to get the sota tools, aklite is note needed
2. NOT SOTA_TOOLS - the goal is to build aklite or other aktualizr's
stuff is not needed (TODO: consider redefing the 'all' target
correspondingly, but it will require updating the bitbake recipe(s))

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Add clang-tidy support

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Output values of the key arguments

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* doc: Adjust README to the latest changes

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* test: Check the sota-tools building

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* doc: Switch from adoc to md

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Move test specifics under tests folder

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Include gtest dir for aklite

sotauptaneclient.h depends on gprod.h (hack), so the aklite has to depend on it
too.

Signed-off-by: Mike Sul <mike.sul@foundries.io>

* Make clang-tidy working

Add BUILD_WITH_CLANG_TIDY build configuration option that makes running
clang-tidy during source compilation. It works per target level.
Fix generation of 'clang-tidy' target for each source file so we can
do 'clang-tidy' check for each source file individually.

Signed-off-by: Mike Sul <mike.sul@foundries.io>

diff --git a/unit-test b/unit-test
--- a/unit-test
+++ b/unit-test
@@ -13,10 +13,25 @@ set -x
 build=$(mktemp -d -p $here)
 cd $build
 
-../cmake-init.sh
-ninja aktualizr-lite t_lite-helpers libt_lite-mock.so uptane-generator make_ostree_sysroot
+# do clang-tidy during compilation
+../cmake-init.sh -DBUILD_WITH_CLANG_TIDY=ON
+ninja aklite-tests
 
+# do additional clang-tidying in the aktualizr way
 ninja aktualizr_clang_tidy-src-helpers.cc  aktualizr_clang_tidy-src-main.cc
 
 ctest -V -R test_lite-helpers
 ctest -V -R test_aktualizr-lite
+
+# test building the sota tools
+rm -rf ./*
+../cmake-init.sh -DBUILD_DOCKERAPP=OFF -DBUILD_SOTA_TOOLS=ON
+ninja all
+if [[ ! -f ./aktualizr/src/sota_tools/garage-sign/bin/garage-sign ]]; then
+  echo "Failed to build garage-sign!"
+  exit 1
+fi
+if [[ ! -f ./aktualizr/src/sota_tools/garage-push ]]; then
+  echo "Failed to build garage-push!"
+  exit 1
+fi
